### ISSUE TITLE
Yahoo table data URL

### ISSUE THREAD

**Issue by solovieff** [pilwon/node-yahoo-finance#21]
At the moment http://real-chart.finance.yahoo.com/table.csv seems to be more up-to-date and accurate, shouldn't it be used instead of old ichart.finance.yahoo.com/table.csv?

**Comment by tjunghans** [comment]
@solovieff seems like both urls are out of date now

**Comment by neverfox** [comment]
Looks like it's now `http://chart.finance.yahoo.com/table.csv`.

**Comment by pilwon** [comment]
Changed to `http://chart.finance.yahoo.com/table.csv` and published as v0.2.14
