### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by Tarang** [pilwon/node-yahoo-finance#36]
The underlying URL seems to have changed today & the library returns no results instead of an expected error (this is an issue too):

```
var yahooFinance = require('yahoo-finance');

yahooFinance.historical({
  symbol: 'AAPL',
  from: '2015-01-01',
  to: '2015-01-02'
}, function (err, quotes) {

  console.log(quotes);

});
```

Returns `[]`

The underlying URL gives an error too:
```
https://chart.finance.yahoo.com/table.csv?s=AAPL
```

**Comment by sarjarapu** [comment]
agreed! Looks like they changed the url about 6 hours ago; not sure where they are getting the crumb from. I tried curl on webpage and make use of the crumb from cookie, it didn't work

https://www.elitetrader.com/et/threads/yahoo-historical-data-did-they-change-the-url-recently.309554/#post-4457665

**Comment by nemozny** [comment]
I confirm.

**Comment by gadicc** [comment]
See above PR.  Not 100% sure when I'll have time to finish it but hopefully within the next week.  Comments welcome and appreciated.  `historical()` is working, might still need some adjustments for `period` input.  Haven't looked at `snapshot()` yet.  Needs some more work for cache invalidation and resiliency.

On another note, @Tarang, @pilwon, hey guys, long time :)

**Comment by gadicc** [comment]
Oh, and @pilwon, I'd like to add some tests, are you ok with that?  Do you have any preferences for test runtime?  mocha, chai/should, sinon, all ok?  Would you prefer it as a separate PR?

Lastly, do you have any views on upgrading to ES7 and shipping via babel?

**Comment by seanlindo** [comment]
If you need something sooner rather than later, I found [Google Finance](https://github.com/pilwon/node-google-finance) to be a drop-in replacement. Same API, just replaced the `import` statement.

**Comment by gadicc** [comment]
@seanlindo, just note though that Google doesn't let you download historical data for all exchanges.  You can see that even on the user facing page, e.g. [NASDAQ:TSLA](https://www.google.com/finance/historical?q=NASDAQ%3ATSLA&ei=h_giWdmDEcG-UdKMqqAK) (see Export option under the chart) vs [HKG:0700](https://www.google.com/finance/historical?q=HKG%3A0700&ei=fvgiWcDSI4SIUdC3vbgO) (no such option).  It's actually why I switched from `node-google-finance` to `node-yahoo-finance`.

**Comment by pilwon** [comment]
Follow the discussions on #37 and #41.
