### ISSUE TITLE
Error: Failed to get crumb (str.trim is not a function)

### ISSUE THREAD

**Issue by buzzcloudau** [pilwon/node-yahoo-finance#50]
I receive this error at startup.

Here is the *sanitised stack trace

`2017-10-20 13:22 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:`
`Error: Failed to get crumb (str.trim is not a function)`
`    at /*/node_modules/yahoo-finance/lib/yahooCrumb.js:72:13`
`    at tryCatcher (/*/node_modules/bluebird/js/release/util.js:16:23)`
`    at Promise._settlePromiseFromHandler (/*/node_modules/bluebird/js/release/promise.js:512:31)`
`    at Promise._settlePromise (/*/node_modules/bluebird/js/release/promise.js:569:18)`
`    at Promise._settlePromise0 (/*/node_modules/bluebird/js/release/promise.js:614:10)`
`    at Promise._settlePromises (/*/node_modules/bluebird/js/release/promise.js:689:18)`
`    at Async._drainQueue (/*/node_modules/bluebird/js/release/async.js:133:16)`
`    at Async._drainQueues (/*/node_modules/bluebird/js/release/async.js:143:10)`
`    at Immediate.Async.drainQueues (/*/node_modules/bluebird/js/release/async.js:17:14)`
`    at runCallback (timers.js:672:20)`
`    at tryOnImmediate (timers.js:645:5)`
`    at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by pilwon** [comment]
Fixed by PR #51. Published as v0.3.5
