### ISSUE TITLE
Error: Failed to download data (status 999)

### ISSUE THREAD

**Issue by Gionni** [pilwon/node-yahoo-finance#53]
Hi,

it's been few days of often struggling but today every classic attempt of getting a snapshot of a symbol gets "Error: Failed to download data (999 - "<html><head><title>Yahoo! - 999 Unable to process request at this time -- error 999</title></head><body>Sorry, Unable to process request at this time -- error 999.</body></html>")".

Any reason? Thanks for any hint, Gionni

**Comment by MikeRixWolfe** [comment]
The text on the [relevant link](http://download.finance.yahoo.com/d/quotes.csv?s=msft&f=price) has been updated to say: 

"It has come to our attention that this service is being used in violation of the Yahoo Terms of Service.  As such, the service is being discontinued.  For all future markets and equities data research, please refer to finance.yahoo.com." 

Looks like the party's over?

**Comment by Gionni** [comment]
Right. This morning I've been looking at it again and it appears exactly your message. Unfortunately.

Do you know alternative ways to get financial indexes? Event paying?

Thanks, G.

**Comment by Gionni** [comment]
I've just read "The fantastic @gadicc is currently working on a fix to support the new API. Please follow PR #42 for the progress". Is it linked to my problem?

Maybe I can help.

**Comment by Gionni** [comment]
Better parsing Yahoo F directly for now.
