### ISSUE TITLE
Non-browsers blocked

### ISSUE THREAD

**Issue by thilomaurer** [pilwon/node-yahoo-finance#67]
Getting exception for quote with price

```js
yahooFinance.quote({
    symbol: "X",
    modules: [ 'price' ]
})
```

https://query2.finance.yahoo.com/v10/finance/quoteSummary/X?modules=price

```33 X stockQuote Error Failed to download data (404 - {"description":"NotFoundException: HTTP 404 Not Found","detail":{"content":["NotFoundException: HTTP 404 Not Found"]},"uri":"http://yahoo.com","lang":"en-US"}) Error: Failed to download data (404 - {"description":"NotFoundException: HTTP 404 Not Found","detail":{"content":["NotFoundException: HTTP 404 Not Found"]},"uri":"http://yahoo.com","lang":"en-US"})```

same via curl:
```
$ curl 'https://query2.finance.yahoo.com/v10/finance/quoteSummary/X?modules=price'
{"description":"NotFoundException: HTTP 404 Not Found","detail":{"content":["NotFoundException: HTTP 404 Not Found"]},"uri":"http://yahoo.com","lang":"en-US"}
```

may be solved by adding `User-Agent` Header 
```
$ curl 'https://query2.finance.yahoo.com/v10/finance/quoteSummary/X?modules=price' -H 'user-agent: Mozilla/5.0'
{"quoteSummary":{"result":[{"price":{"maxAge":1,"preMarketChangePercent .......
```

Seems that yahoo blocks non-browsers....

**Comment by thilomaurer** [comment]
Well, no seems that did only work for a short amount of time.
Now it does not even work in the browser itself.

**Comment by thilomaurer** [comment]
Yes, even yahoo's own website throws errors. Maybe this can be closed tomorrow.

**Comment by gadicc** [comment]
Thanks for following up, @thilomaurer!  Yes, it seems many of the errors reported here relate back to transient errors on Yahoo's CDN which resolve themselves in short order.
