### ISSUE TITLE
NextJS 13 get data during the build

### ISSUE THREAD

**Issue by SergeySypalo** [pilwon/node-yahoo-finance#87]
Hi there,

Thatnks first of all for this awesome library.

I'm using it to get [best stocks](https://sypalo.com/best-stocks), but looking at the PageSpeed reports from Google console it turned out that data fetching is done on client side, even that npm build tells me that page is statically generated HTML + JSON.

So my question, is there a way to run data fetching during the build, maybe leveraging webpack somehow?
Also the lib is still works when using current approach, but when I tried to move migrate to a new one when _app.js and _document.js is replaced by single layout.js file, build failed.

You can try youself by simply create a new NextJS 13 project and including this library in it.

**Comment by geovanisouza92** [comment]
@SergeySypalo You should look for [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) and if you want that data to be updated from time to time but still leverage static content, you should use [ISR](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration).

**Comment by SergeySypalo** [comment]
Thanks @geovanisouza92, it turned out to be a problem with Javascript/ChartJS execution time, it took quite a while to draw charts for a number of stocks, so I ended up switching to generating images with price charts monthly.
